name: Build License Keygen

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x86' # Ensures 32-bit Python is installed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build 32-bit Executable
      run: |
        mkdir -p "dist/License Keys" # Create target folder for the executable
        pyinstaller --onefile --noconsole --platform=win32 license.py
        move "dist\license.exe" "dist\License Keys\license.exe"

    - name: Verify Build Output
      run: |
        dir "dist\License Keys" # List the contents of the output directory to confirm

    - name: Upload Executable to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "dist/License Keys/license.exe"
        git commit -m "Add generated executable: License Keys/license.exe"
        git push

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: license-keygen-executable
        path: dist/License Keys/license.exe
