name: Build License Keygen

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x86' # Ensures 32-bit Python is installed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) {
          pip install -r requirements.txt
        }
      shell: pwsh

    - name: Build 32-bit Executable
      run: |
        New-Item -ItemType Directory -Path "dist/License Keys" -Force
        pyinstaller --onefile --noconsole license.py
      shell: pwsh

    - name: Verify and Move Build Output
      run: |
        if (-Not (Test-Path "dist/license.exe")) {
          Write-Error "Executable not found! Build failed."
          exit 1
        }
        New-Item -ItemType Directory -Path "dist/License Keys" -Force
        Move-Item "dist/license.exe" "dist/License Keys/license.exe"
      shell: pwsh

    - name: Upload Executable to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "dist/License Keys/license.exe"
        git commit -m "Add generated executable: License Keys/license.exe"
        git push
      shell: pwsh

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: license-keygen-executable
        path: dist/License Keys/license.exe
